# This is a basic workflow that is manually triggered

name: Create XPI workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Create XPI file'
        # Default value if no value is explicitly provided
        default: '0.8.3'
        # Input has to be provided for the workflow to run
        required: true

env:
   ADDIN_NAME: JoinNG
   MAJOR: 0
   MINOR: 8.3
   APP: tb

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make an Thunderbird add-in
      run: |
        zip -r ${ADDIN_NAME}_$MAJOR.$MINOR-$APP.xpi src/*
    - name: Commit file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git add ${ADDIN_NAME}_$MAJOR.$MINOR-$APP.xpi
        git commit -m "${ADDIN_NAME}_$MAJOR.$MINOR-$APP.xpi created" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
