# This is a basic workflow that is manually triggered

name: Create XPI workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Create XPI file'
        # Default value if no value is explicitly provided
        default: '0.8.3'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This creates an XPI file
  XPI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Create XPI
      run: cd src && zip -r ../join-ng.xpi *
      
 Clean:
    runs-on: ubuntu-latest
    steps:
    - name: Clean XPI
      run: rm -f join-ng.xpi
      
