# This is a basic workflow that is manually triggered

name: Create XPI
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      ADDIN_NAME:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Add-in name'
        # Default value if no value is explicitly provided
        default: 'JoinNG'
        # Input has to be provided for the workflow to run
        required: true
      MAJOR:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Major revision number'
        # Default value if no value is explicitly provided
        default: '0'
        # Input has to be provided for the workflow to run
        required: true
      MINOR:
        description: 'Minor revision number'
        default: '8.3'
        required: true
      APP:
        description: 'Application flavor'
        default: 'tb'
        required: true
    
      

#env:
#   ADDIN_NAME: JoinNG
#   MAJOR: 0
#   MINOR: 8.3
#   APP: tb

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Make an Thunderbird add-in
      run: |
        cd src && zip -r ../$INPUT_ADDIN_NAME_${INPUT_MAJOR}.${INPUT_MINOR}-${INPUT_APP}.xpi *
    - name: Commit file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull
        git add $INPUT_ADDIN_NAME_${INPUT_MAJOR}.${INPUT_MINOR}-${INPUT_APP}.xpi
        git commit -m "$INPUT_ADDIN_NAME_${INPUT_MAJOR}.${INPUT_MINOR}-${INPUT_APP}.xpi created" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
