name: Create XPI
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
# Inputs the workflow accepts.
    inputs:
      addin_name:
        description: 'Add-in name'
#       Default value if no value is explicitly provided
        default: 'JoinNG'
#       Input has to be provided for the workflow to run
        required: true
      major:
        description: 'Major revision number'
        default: '0'
        required: true
      minor:
        description: 'Minor revision number'
        default: '8.6'
        required: true
      app:
        description: 'Application flavor'
        default: 'tb'
        required: true
      
#env:
#    ADDIN_NAME: JoinNG
#    MAJOR: 0
#    MINOR: 8.3
#    APP: tb

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Make an Thunderbird add-in
          run: |
            echo "Creating ${{ github.event.inputs.addin_name }}_${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}-${{ github.event.inputs.app }}.xpi"
            cd src && zip -r ../${{ github.event.inputs.addin_name }}_${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}-${{ github.event.inputs.app }}.xpi *
        - name: Commit file
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            git add ${{ github.event.inputs.addin_name }}_${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}-${{ github.event.inputs.app }}.xpi
            git commit -m "${{ github.event.inputs.addin_name }}_${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}-${{ github.event.inputs.app }}.xpi created" -a
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
